# Generated by Django 3.1.2 on 2020-11-27 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppemsapp', '0004_todolist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('head_of_dept', models.CharField(max_length=250)),
                ('number_of_employe', models.IntegerField(blank=True, null=True)),
                ('access_number', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
