# Generated by Django 3.1.2 on 2020-11-27 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppemsapp', '0005_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='head_of_dept',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
