# Generated by Django 3.1.2 on 2020-11-28 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppemsapp', '0009_auto_20201128_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='static/img/si.png', null=True, upload_to=''),
        ),
    ]
