# Generated by Django 3.1.2 on 2020-12-12 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppemsapp', '0013_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='used_status',
            field=models.BooleanField(default=False),
        ),
    ]
